# Generated by Django 6.1 on 2026-08-14 11:09

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckInSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата заїзду')),
                ('start_time', models.TimeField(verbose_name='Час заїзду (Check-in)')),
                ('end_time', models.TimeField(verbose_name='Час виїзду (Check-out)')),
                ('available_spots', models.PositiveIntegerField(verbose_name='Доступно вільних номерів')),
            ],
            options={
                'verbose_name': 'Сеанс заїзду',
                'verbose_name_plural': 'Сеанси заїзду',
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_inventory', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Загальна кількість таких номерів у готелі')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Базова ціна')),
                ('amenities', models.JSONField(blank=True, default=list, verbose_name='Зручності (Wi-Fi, кондиціонер тощо)')),
            ],
            options={
                'verbose_name': 'Тип номеру',
                'verbose_name_plural': 'Типи номерів',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата та час бронювання')),
                ('status', models.CharField(choices=[('pending', 'Очікує оплати'), ('paid', 'Оплачено'), ('cancelled', 'Скасовано')], default='pending', max_length=20, verbose_name='Статус')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Загальна вартість')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='Клієнт')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='booking.checkinsession', verbose_name='Сеанс заїзду')),
            ],
            options={
                'verbose_name': 'Бронювання',
                'verbose_name_plural': 'Бронювання',
            },
        ),
        migrations.AddField(
            model_name='checkinsession',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkinsessions', to='booking.room', verbose_name='Кімната у готелі'),
        ),
    ]
