# Generated by Django 6.1 on 2026-08-14 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Room',
            new_name='RoomType',
        ),
    ]
