# Generated by Django 6.1 on 2026-08-17 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_rename_room_roomtype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkinsession',
            old_name='title',
            new_name='room',
        ),
    ]
