# Generated by Django 6.0.5 on 2026-08-18 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_rename_title_checkinsession_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='description',
            field=models.TextField(blank=True, verbose_name='Опис'),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='rooms',
            field=models.PositiveIntegerField(default=1, verbose_name='Кількість кімнат у номері'),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='title',
            field=models.CharField(default='Без назви', max_length=100, verbose_name='Назва'),
            preserve_default=False,
        ),
    ]
