# Generated by Django 6.0.5 on 2026-08-18 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_roomtype_description_roomtype_rooms_roomtype_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkinsession',
            name='end_time',
        ),
        migrations.AddField(
            model_name='checkinsession',
            name='check_out',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата та час виїзду'),
        ),
    ]
