# Generated by Django 6.0.5 on 2026-08-18 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_remove_checkinsession_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Кількість номерів'),
        ),
    ]
