# Generated by Django 6.1 on 2026-08-19 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_booking_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=50, verbose_name="Ім'я гравця")),
                ('game_name', models.CharField(max_length=50, verbose_name='Назва гри')),
                ('score', models.IntegerField(verbose_name='Результат')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Час створення')),
            ],
            options={
                'ordering': ['-score'],
            },
        ),
    ]
